name: maven-install
on:
  push:
    branches:
      - main
jobs:
  maven-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-install
          restore-keys: maven-repo-
      - run: mvn clean install
