name: maven-pre-site
on:
  schedule:
    - cron: '11 0 20-26 * *'
jobs:
  maven-pre-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-pre-site
          restore-keys: maven-repo-
      - uses: actions/cache@v4
        with:
          path: ~/.cache/opennlp-model-generator
          key: opennlp-model-cache-${{ github.run_id }}
          restore-keys: opennlp-model-cache-
      - run: mvn clean install
      - run: mvn -Dmax.exec.minutes=333 pre-site
