name: maven-dry-run
on:
  push:
    branches:
      - main
jobs:
  maven-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-dry-run
          restore-keys: maven-repo-
      - uses: actions/cache@v4
        with:
          path: ~/.cache/opennlp-model-generator
          key: opennlp-model-cache-${{ github.run_id }}
          restore-keys: opennlp-model-cache-
      - run: mvn clean install
      - run: mvn -Dlanguage.codes=el site
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site
          branch: gh-pages
          git-config-name: abzif
          git-config-email: abzif@users.noreply.github.com
          commit-message: 'Site publish'
          single-commit: true
          dry-run: true
